In [3]:
!pip install torch==1.11.0 torchvision==0.12.0 torchaudio==0.11.0
import numpy as np
import torch

In [5]:
## 텐서 초기화
data = [[1,2], [3,4]]
x_data = torch.tensor(data)
print(x_data)

tensor([[1, 2],
        [3, 4]])


In [7]:
## Numpy 배열로부터 생성하기
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
print(x_np)

x_ones = torch.ones_like(x_data) # x_data의 속성을 유지한다.
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # x_data의 속성을 덮어쓴다.
print(f"Random Tensor: \n {x_rand} \n")

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)
Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.4228, 0.9841],
        [0.3032, 0.8713]]) 



In [8]:
## 무작위 또는 상수 값을 사용하기
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)
print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.0037, 0.3424, 0.0940],
        [0.4649, 0.6017, 0.0199]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [9]:
## 텐서의 속성
tensor = torch.rand(3,4)
print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [17]:
## 텐서의 연산
# GPU에서 더욱 빠르게 동작
# GPU가 존재하면 텐서를 이동
if torch.cuda.is_available():
    tensor = tensor.to('cuda')
    print(f"Device tensor is stored on: {tensor.device}")

# Numpy식의 표준 인덱싱과 슬라이싱
tensor = torch.ones(4, 4)
tensor[:,1] = 0
print(tensor, "\n")

# 텐서 합치기
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1, "\n")

# 텐서 곱하기
print(f"tensor.mul(tensor) \n {tensor.mul(tensor)} \n")

# 두 텐서간의 행렬 곱
print(f"tensor.matmul(tensor.T) \n {tensor.matmul(tensor.T)} \n")

# 바꿔치기
# 연산 _접미사를 갖는 연산들은 바꿔치기(in-place)연산이다.
# -> x.copy()나 x.t_()는 x를 변경한다.
# 메모리를 절약할 수 있지만 기록이 즉시 삭제되어 도함수 계산이 문제 발생할 수 있다.
print(tensor, "\n")
tensor.add_(5)
print(tensor)


tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]]) 

tensor.mul(tensor) 
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor.matmul(tensor.T) 
 tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]]) 

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


In [18]:
# Numpy 변환(Bridge)
# CPU 상의 텐서와 Numpy 배열은 메모리 공간을 공유하기 떄문에 ,하나를 변경하면 다른 하나도 변경된다.

# 텐서를 Numpy 배열로 변환
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

# 텐서의 변경사항이 Numpy 배열에 반영
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]
t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


In [19]:
# NumPy배열을 텐서로 변환하기
n = np.ones(5)
t = torch.from_numpy(n)

# NumPy배열의 변경 사항이 텐서에 반영됩니다.
np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]


In [22]:
# 뷰(View) - 원소의 수를 유지하면서 텐서의 크기 변경
# 파이토치 View == 넘파이 Reshape
t = np.array([[[0, 1, 2], [3, 4, 5]], [[6, 7, 8], [9, 10, 11]]])
ft = torch.FloatTensor(t)
print(ft.shape)

# 3차원 -> 2차원 (크기만 변환)
print(ft.view([-1, 3])) # ft라는 텐서를 (?(랜덤값), 3)의 크기로 변경
print(ft.view([-1, 3]).shape)

# 3차원 -> 3차원 (크기만 변환)
print(ft.view([-1, 1, 3]))
print(ft.view([-1, 1, 3]).shape)

torch.Size([2, 2, 3])
tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])
tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])


In [24]:
# 스퀴즈(Squeeze) : 1인 차원을 제거
ft = torch.FloatTensor([[0], [1], [2]])
print(ft)
print(ft.shape)

# 값이 1인 두번째 차원을 제거
print(ft.squeeze())
print(ft.squeeze().shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])
tensor([0., 1., 2.])
torch.Size([3])


In [27]:
# 언스퀴즈(Unsqueeze) : 특정 위치에 1인 차원을 추가한다.
ft = torch.Tensor([0, 1, 2])
print(ft.shape)

print(ft.unsqueeze(0)) # 인덱스가 0부터 시작하므로 0은 첫번째 차원을 의미한다.
print(ft.unsqueeze(0).shape)

print(ft.view(1, -1))
print(ft.view(1, -1).shape)

torch.Size([3])
tensor([[0., 1., 2.]])
torch.Size([1, 3])
tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [30]:
ft = torch.Tensor([0, 1, 2])
print(ft.shape)

print(ft.unsqueeze(1)) # 인덱스가 1이므로 두번째 차원에 1 추가
print(ft.unsqueeze(1).shape)

print(ft.unsqueeze(-1)) # 인데스 -1은 마지막 차원에 1 추가
print(ft.unsqueeze(-1).shape)

torch.Size([3])
tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])
tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])
