In [3]:
import sklearn
from sklearn.preprocessing import *
import numpy as np
from numpy import *

In [7]:
# 정규화 Standardization
def normalization(data):
    data_mm = (data - data.min(axis = 0)) / (data.max(axis = 0) - data.min(axis = 0))
    return data_mm

# Nomalization 와 정규화 Standardization
def numpy_standardization(data):
    '''
    (각데이터 = 평균(각열)) / 표준편차(각열)
    '''
    std_data = (data - np.mean(data, axis = 0) / np.std(data, axis = 0))
    return std_data

def main():
    data = np.random.randint(30, size=(6,5))
    # print(data)
    print('표준화 데이터')
    std_data_temp = numpy_standardization(data)
    print(std_data_temp)

    print('정규화 데이터')
    no_data = normalization(data)
    print(no_data)

if __name__ == '__main__':
    main()

표준화 데이터
[[22.20829517 17.05405848  6.14417283 21.41541583  7.22430451]
 [ 5.20829517 21.05405848 25.14417283 25.41541583 27.22430451]
 [21.20829517 13.05405848  5.14417283  8.41541583  1.22430451]
 [11.20829517 15.05405848 17.14417283  3.41541583 16.22430451]
 [16.20829517  3.05405848 10.14417283  3.41541583  9.22430451]
 [26.20829517 21.05405848  6.14417283  9.41541583 16.22430451]]
정규화 데이터
[[0.80952381 0.77777778 0.05       0.81818182 0.23076923]
 [0.         1.         1.         1.         1.        ]
 [0.76190476 0.55555556 0.         0.22727273 0.        ]
 [0.28571429 0.66666667 0.6        0.         0.57692308]
 [0.52380952 0.         0.25       0.         0.30769231]
 [1.         1.         0.05       0.27272727 0.57692308]]
