In [1]:
import cv2

In [2]:
img_path = "./cat.png"
img = cv2.imread(img_path)
print(img)

[[[244 238 233]
  [244 238 233]
  [244 238 233]
  ...
  [247 236 232]
  [247 236 232]
  [248 237 233]]

 [[244 238 233]
  [243 237 232]
  [245 239 234]
  ...
  [248 237 233]
  [248 237 233]
  [248 237 233]]

 [[245 239 234]
  [244 238 233]
  [244 238 233]
  ...
  [248 238 231]
  [249 239 232]
  [248 238 231]]

 ...

 [[251 247 246]
  [251 247 246]
  [251 247 246]
  ...
  [252 249 245]
  [254 249 246]
  [254 249 246]]

 [[252 248 247]
  [252 248 247]
  [252 248 247]
  ...
  [253 250 246]
  [255 250 247]
  [253 248 245]]

 [[252 248 247]
  [251 247 246]
  [252 248 247]
  ...
  [253 250 246]
  [254 249 246]
  [254 249 246]]]


In [5]:
h, w, _ = img.shape

print("이미지 타입 : ", type(img))
# print("이미지 크기 : ", img.shape) # (Height, width, channel)
print(f"이미지 높이 {h}, 이미지 넓이 {w}")

이미지 타입 :  <class 'numpy.ndarray'>
이미지 높이 399, 이미지 넓이 600


In [4]:
cv2.imshow("image show", img)
cv2.waitKey(0)

-1