In [2]:
!pip install opencv-python==4.5.5.62 # open CV는 최신버전보다 이전 버전이 호환성이 더 좋다. 만약 오류발생 시 삭제 후 다시 설치 권장
import numpy as np
import cv2


[notice] A new release of pip available: 22.3 -> 22.3.1
[notice] To update, run: C:\Users\user\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip


In [3]:
# 이미지 경로
x = cv2.imread("./cat.png", 0) # 흑백 이미지
print(x)
y = cv2.imread("./cat.png", 1) # 컬러 이미지

[[237 237 237 ... 236 236 237]
 [237 236 238 ... 237 237 237]
 [238 237 237 ... 237 238 237]
 ...
 [247 247 247 ... 248 249 249]
 [248 248 248 ... 249 250 248]
 [248 247 248 ... 249 249 249]]


In [4]:
img = cv2.resize(x,(200,200))
# cv2.imshow("cat image show gray", img)
# cv2.imshow("cat image show", y)
# cv2.waitKey(0)

-1

In [5]:
# 여러개 파일 save .npz
np.savez("./image.npz", array1 = x, array2 = y)

# 압축 방법
np.savez_compressed("./image_compressed.npz", array1 = x, array2 = y)

In [6]:
# npz 데이터 로드
data = np.load("./image_compressed.npz")
result1 = data['array1']
result2 = data['array2']

cv2.imshow("result01", result1)
cv2.waitKey(0)

-1